### PR TITLE
midpoint

### PR DESCRIPTION
**Pull request by Cris7777**
**load_data_from_git:** download data from a GitHub repo to ../data/data1.csv

**upload_data_to_s3:** upload data to target s3 bucket, be sure to configure the aws credential in advance

_Parameters to be specified:_

--input_path: local file path. In this case, ../data/data1.csv

--bucket_name: target bucket name

--output_path: output file path

**create_rds_db:** either create a local db or a rds table

_Parameters to be specified:_

--RDS: True to create rds table, default to create local db

_Note:_ Table created can be checked in the 'logfile'

### CODE REVIEW

**Comment by Ivanclj** [comment]
## Functionality

The code is doing what it's meant to do. 


## Readability and code quality

The code is easy to follow.

The design decision is easy to understand as it matches what is in the backlog and charter.

It is clear in both individual script and the whole code base.

The variable and methods names are meaningful and easy to follow what they are referencing.

Methods/fuctions are appropriately sized and no functions need to be broken apart. 


## Overall design

The code being reviewed make sense in large context and is consistent with the general approach.

It is modular and extensible.

There are no visible issues to impact future development.

## Test 
The code is structured easily for testing.

The PR does not include necessary tests.


## Documentation
Some methods does not have docstrings.

Yes the inputs and outputs are explained and referenced.

There are comments to aid others to understand what is being done.


## README.md 

README need to modify and add new instructions for how to run the code in.

**Comment by Cris7777** [comment]
which type of test should I include?

**Comment by Cris7777** [comment]
which type of test should I include?

**Comment by Cris7777** [comment]
Docstring added to src/sql/create_rds_db.py

**Comment by Ivanclj** [comment]
> which type of test should I include?

I think you test for downloading the data is necessary

**Comment by Cris7777** [comment]
> > which type of test should I include?
> 
> I think you test for downloading the data is necessary

Gotcha, thanks

**Pull request merged**
